# Must use the format of this export command
# conda env export --from-history -f environment.yml
#
name: environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - nltk
  - sklearn
